### ISSUE TITLE
Проверка за валута в базата на база локация

### ISSUE THREAD

**Issue by Tsvetoslav88** [petarov/bgrates#16]
За да се определи дали в базата има валути и дали да се извика изчитането на XML-ла, се изпълнява следния код: source.getRates(getSelectedCurrenciesLocale());. За потребител, който е с локация BG, никога няма да провери дали има EN. 
Предложение - да се проверяват и 2-те локации, независимо коя му е сетната?

**Comment by petarov** [comment]
Хмм, това май не би трябвало да е фатално? В смисъл, че `BNBSource.java` винаги ще дърпа и EN и BG в базата, така че каквото и да провери `source.getRates`, то в базата трябва да имаме и 2-те. 

Или ти визираш частен случай, в който поради някаква причина имаме BG, а не EN в базата?

**Comment by Tsvetoslav88** [comment]
В сайта на БНБ по някаква причина се качва само единия файл(BG)(или по късно се качва другия(EN)). То в базата се записва само BG. След което се прави проверка дали за локализацията, която е сетната има валута List<CurrencyData> ratesList = source.getRates(getSelectedCurrenciesLocale());->има по описаната по-горе причина. При което useRemoteSource си стой винаги на false, защото има валута BG, при което не се изпълнява:
if (useRemoteSource) {
	setRefreshActionButtonState(true);
	new UpdateRatesTask().execute();
}
Ако бъркам/пропускам или според теб е невъзможно това да се случи - ме поправи?

**Comment by petarov** [comment]
Ще го обсъдим това live ;)

**Comment by Tsvetoslav88** [comment]
Дискутиран и изяснен въпроса - проблем няма!
