### ISSUE TITLE
Добавяне на фиксирани валути 

### ISSUE THREAD

**Issue by petarov** [petarov/bgrates#21]
Част от валутните курсове са фиксирани и трябва да се добавят към списъка.

**Comment by petarov** [comment]
`Fixed` в модела.

**Comment by Tsvetoslav88** [comment]
- [ ] - Добавяне на нов елемент в CurrencyDate модела

**Comment by Tsvetoslav88** [comment]
Част от тикетите са направени със Commits on Jan 5, 2016
