### ISSUE TITLE
Проблем със Code Formatter в Android Studio

### ISSUE THREAD

**Issue by Tsvetoslav88** [petarov/bgrates#25]
В Android Studio е сложен Code Formatter , който се е ползвал досега в Eclipse. От: Settings -> Other Settings ->Eclipse Code Formatter, но има проблем с форматирането на кода - не работи.

**Comment by petarov** [comment]
Това не успях до момента да го оправя. Уж всичко е наместено, но май няма ефект. Ще го гледаме ...
