### ISSUE TITLE
Нормализация на базата от данни

### ISSUE THREAD

**Issue by petarov** [petarov/bgrates#7]
- [x] Нова колона за локализацията на дадена валута в таблица currencies
- [x] Нова таблица, която съдържа само дати, на които са изтеглени валути
- [x] Преправяне на наследените методи:
  - [x] Method addRates да пише в новата таблица деня на въвеждане на валутата
  - [x] Method addRates да прави проверка дали има валута за подадената дата
  - [x] Method getAvailableRatesDates да чете от новата таблица
- [x] Нов method и interface, който чете последно въведените дати в базата

**Comment by Tsvetoslav88** [comment]
Closed issue with commit  f9a28052d02d12b0e6afbb0bb0158394220b6d4b
